type: 'enn'
backbone: 'cvt'
dataset: 'nuscenes'
logdir: 'nuscenes/cvt_enn_f'
pretrained: 'nuscenes/cvt_enn/best_iou.pt'
gpus: [0]
batch_size: 32
num_workers: 16
weight_decay: 0.0000001
learning_rate: 0.001
num_steps: 40000
val_step: 1000