type: 'enn_uce'
logdir: 'nuscenes/enn_uce'
gpus: [2,3]
dataset: 'nuscenes'
batch_size: 32
num_workers: 64
weight_decay: 0.0000001
learning_rate: 0.001
num_epochs: 100
val_step: 200
pretrained: './carla/enn_ce/best.pt'
