data_path: '../data/carla'
type: 'baseline_ce'
model: 'BEVDet'
gpus: [4,5,6,7]
dataset: 'nuscenes'
batch_size: 64
num_workers: 64
weight_decay: 0.0000001
learning_rate: 0.001
num_epochs: 100
val_step: 500