type: 'postnet_uce_cnn'
logdir: 'carla/postnet_uce_cnn'
gpus: [1,7]
dataset: 'carla'
batch_size: 32
num_workers: 64
weight_decay: 0.0000001
learning_rate: 0.001
num_epochs: 100
val_step: 1000
pretrained: './carla/postnet_ce_cnn/model48000.pt'
