type: 'dropout'
backbone: 'lss'
dataset: 'nuscenes'
logdir: 'nuscenes/lss_dropout'
gpus: [5]
batch_size: 32
num_workers: 16
weight_decay: 0.0000001
learning_rate: 0.001
num_steps: 20000
val_step: 1000